### ISSUE TITLE
App update notification 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam#1071]
1) Show update alert once https://zpl.io/V15KWWm
2) Add "update" button on settings screen https://zpl.io/2GRqEN9
3) Open alert https://zpl.io/aR05BDr if "Allow access to beam.mw and blockchain explorer (to fetch exchanges and transaction data)" turned off.

**Comment by Zeke133** [comment]
New design off update pop-up: [is here](https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5e33a0feefc06052f8263983)

**Comment by Denis-Asipenko** [comment]
1.In settings missing button.
![image](https://user-images.githubusercontent.com/45556620/75443105-c8026c80-5971-11ea-92fb-ade558940485.png)
2.different text in warning.
![image](https://user-images.githubusercontent.com/45556620/75442754-2b3fcf00-5971-11ea-8798-e8baf4ab4363.png)
3.The switch in settings(**Allow access to beam.mw and blockchain explorer (to fetch exchanges and transaction data**)) is activated if I click "open".

**Comment by Denis-Asipenko** [comment]
Please change the text the button of the with "allow and open" to "allow and open web-site".
Note: the changes apply to cases when the user is redirected to our site.
![image](https://user-images.githubusercontent.com/45556620/76082235-ebee2f80-5fbb-11ea-8e3e-9c9789593e96.png)

**Comment by dariatarakanova** [comment]
Here is updated alert: https://zpl.io/bApk4M6

1) Change the title
2) Change the text
3) Add check-box with text "allow open links"
4) Leave buttons "cancel" and "open web-site"

This alert the same for all external links. 
If user once marked the check-box - do not show this alert any more. 
If user doesn't mark the check-box - show this alert every time.

**Comment by VladislavKulyba** [comment]
1. The link from Update button leads to main screen instead of downloads page. Please, delete # in this link https://beam.mw/#downloads
![Snag_6c0387f](https://user-images.githubusercontent.com/51320829/76536492-7ab3ee00-648d-11ea-969d-755c963c45a5.png)
2. In the alert (https://zpl.io/bApk4M6) the button "cancel" is highlighted every time when you press on Update button. There is the same issue for "Where to buy BEAM" icon. 
![photo_2020-03-12_16-30-43](https://user-images.githubusercontent.com/51320829/76536702-c49cd400-648d-11ea-838d-04d349a77889.jpg)
For other links (beam.mw, blockchain explorer, support@beam.mw, Github) the button "cancel" is highlighted only for the first opening. 
[links.zip](https://github.com/BeamMW/beam/files/4325045/links.zip)

**Comment by Denis-Asipenko** [comment]
checked
