### ISSUE TITLE
[Blocks Explorer]Block Browser cannot query transactions via transaction Id

### ISSUE THREAD

**Issue by wshhz** [BeamMW/beam#1117]
**Feature title**
In the block browser, I hope to query the transaction information through the transaction Id.

**Describe the current situation we have**
Block Browser cannot query transactions via transaction Id

**Comment by anatolse** [comment]
Node explorer doesn't allow to query transactionss via id since node doesn't store separate transactions. Tx Id is used only by wallets to identify transactions during negotiation phase (when wallets have to send messages to each other to sign a transaction data), thus wallet never sends tx id to the node and node knows nothing about tx id.
