### ISSUE TITLE
Why the same txid returns different results on two different nodes ？

### ISSUE THREAD

**Issue by Alteryy** [BeamMW/beam#1550]
One status is 3, the other status is 4, and the reason for failure: Transaction timed out.

node1 to receive:
{
    "id":1,
    "jsonrpc":"2.0",
    "result":{
        "asset_id":0,
        "comment":"",
        "create_time":1595597765,
        "failure_reason":"Transaction timed out",
        "fee":100,
        "income":true,
        "receiver":"f65aad151c0f13f4f66fdf16fe3876737a03810d779422db26730c90dc57bf69ef",
        "sender":"3fb408845236b05fbfbf991a10517cbda8e8b276b98fe0f40b4cb218a6b3fa39eba",
        "status":4,
        "status_string":"expired",
        "txId":"1ae48dbdad3c4c41b7d7dbc1ec20ec6d",
        "tx_type":0,
        "tx_type_string":"simple",
        "value":914190000000
    }
}

node2 to send:
<img width="716" alt="beam-respand" src="https://user-images.githubusercontent.com/25837579/88757913-bed43080-d199-11ea-9e5c-c8024142589c.png">

**Comment by anatolse** [comment]
Hello! I see that on the sender side transaction is completed, but on receiver's wallet-api reports that it has timed out. Usually, this means that receiver has two instancies of the wallet (cli, api, desktop, mobile, ), running simultaneously with the same seed and with the same list of active addresses. During the wallet negotiation phase of the beam transaction, sender sends an invitation to the address of the receiver, all instances of the receiver may accept this transaction, but with different nonces. It's a race condition: only one instance will get Completed transaction, the others will fail since transactions with their kernel ID were never send to the blockchain. This is a known case that goes from the interactive nature of MimbleWimble protocol. If your wallets are connected to the node with the owner key, then the balance should be correct on all wallet instancies. Please, check that you have other instances of the wallet, one of them should have completed transaction with same txid and with kernel id = 809e1102d58b44f4c9282176cb91f8d4c106280e62d633ce57dec3813fdc015f

**Comment by Alteryy** [comment]
> Hello! I see that on the sender side transaction is completed, but on receiver's wallet-api reports that it has timed out. Usually, this means that receiver has two instancies of the wallet (cli, api, desktop, mobile, ), running simultaneously with the same seed and with the same list of active addresses. During the wallet negotiation phase of the beam transaction, sender sends an invitation to the address of the receiver, all instances of the receiver may accept this transaction, but with different nonces. It's a race condition: only one instance will get Completed transaction, the others will fail since transactions with their kernel ID were never send to the blockchain. This is a known case that goes from the interactive nature of MimbleWimble protocol. If your wallets are connected to the node with the owner key, then the balance should be correct on all wallet instancies. Please, check that you have other instances of the wallet, one of them should have completed transaction with same txid and with kernel id = 809e1102d58b44f4c9282176cb91f8d4c106280e62d633ce57dec3813fdc015f

ok.thanks
