### ISSUE TITLE
User should be able receive and send max privacy txs via cli wallet

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#1554]
Add ability for a user to receive and send max privacy txs via CLI wallet

**Comment by Denis-Asipenko** [comment]
Need to add:
1. Flag\command to generate a token so that the user can get the max privacy transaction.
2. Show an error message if the user-specified was less than the allowed Fee when sending the transaction.
![image](https://user-images.githubusercontent.com/45556620/90645223-5f1ff100-e23e-11ea-9830-4b1b19f0e02c.png)

**Comment by KatsiarynaV** [comment]
Not fixed: When user send transaction with regular coins to max privacy token from CLI wallet and use fee less than the allowed an error message should appear
![900](https://user-images.githubusercontent.com/68267190/91872584-aff10a00-ec80-11ea-8d9f-eefc3b11fc47.jpg)

**Comment by Denis-Asipenko** [comment]
The check will continue after this error is fixed https://github.com/BeamMW/beam/issues/1555#issuecomment-690104260

**Comment by Denis-Asipenko** [comment]
checked
