### ISSUE TITLE
About treasury.bin

### ISSUE THREAD

**Issue by foqer** [BeamMW/beam#1563]
hi:

https://github.com/BeamMW/beam/blob/master/treasury.bin

Why is it not open source?

what's this?

**Comment by gingervik** [comment]
Hello. This is a treasury file.
We believe a startup environment is best for innovation, that's why we are raising money. Treasury model is the best way to repay our investors and to provide a reward to the founding team. Treasury works in the following way: in the first five years of Beam existence, 20% of all emitted coins automatically go to the Treasury. Technically, the additional coins are emitted for each mined block. Our investors, the core team, our advisors and the non-profit Beam Foundation will be getting Beam coins from the Treasury on a monthly basis. We believe that the five year payout period creates an alignment of interest between all the parties and ensures that our coin will get the support it requires to succeed.
Our project is open-source.
