### ISSUE TITLE
Transactions are sent to max privacy online address when the wallet is closed

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam#1586]
When 1 transaction was sent to the max private address and received in another wallet. Then the next transactions are sent when the other wallet is closed.

Precondition:
There're 2 wallets A and B

Step
- (A) open receive screen and copy max_privacy online address
- (B) open send screen 
- (B) paste the copied address, enter any amount, and send 
- (B)wait for the transaction to get the sent status.
- (A)close wallet 
- (B) send transaction again to this address

Expected: transaction gets status 'waiting for receive'
Actual: Transaction is sent 
Build: 5.2.9576.3185
[Video.zip](https://github.com/BeamMW/beam/files/5220046/Video.zip)
[Wallet A logs.zip](https://github.com/BeamMW/beam/files/5220053/Wallet.A.logs.zip)
[Wallet B logs.zip](https://github.com/BeamMW/beam/files/5220055/Wallet.B.logs.zip)

**Comment by anatolse** [comment]
It's by design. When you are trying to send to the online token for the first time the sender doesn't have any voucher and it asks the receiver for the list of the vouchers via SBBS. After that, on the second attempt to send, the sender already has the voucher and it doesn't need the receiver to be online
