### ISSUE TITLE
Install wallet usb beam in tails os. sudo dpkg -i beam wallet.....deb, successful.  but when it runs stuck in the build wallet

### ISSUE THREAD

**Issue by soeb168** [BeamMW/beam#1598]
**Feature title**
Express the feature in a single concise sentence

**Describe the current situation we have**
Please bring in the relevant context: what are you suggesting to achieve vs what the current situation is. 

**Describe the solution you'd like**

**Describe alternatives you've considered (if relevant)**

**Additional context**

**Comment by vcorem** [comment]
I'm offering 2K Beam bounty for whoever completes this task + writing a concise howto article.

**Comment by giaki3003** [comment]
> I'm offering 2K Beam bounty for whoever completes this task + writing a concise howto article.

Maybe write a complete report for a bug you're running a bounty on?

**Comment by tperalta82** [comment]
There's an easy fix, (my wallet is syncing as of now) and a not so easy fix (that i'm trying to work on at the moment)
This is due to Tails OS relying on the Tor network and socks proxy and iptables rules, thus the wallet cannot connect to any outside nodes.

the easy fix is:
sudo iptables -I INPUT -p tcp --dport 8100 -j ACCEPT 

Not sure what other outside ports mimble may use, but the simple way is to add them like I did with the command above


![image](https://user-images.githubusercontent.com/4300670/95022272-1a291000-066e-11eb-8322-1af8467100f7.png)

BEAM: 320e47e9264e1659b20c4e60d6ecb863b548804a6b8fc088d2145a80012f5ba4a25

If you want to wait for the not so easy fix, i'm gonna need some more time, and i'm not even sure it'll work.

**Comment by sgaragagghu** [comment]
Haha @tperalta82 found a fix 5 minutes before me, so compliments. :clap:

My fix is use proxychains.
`sudo apt install proxychains`
And then start the wallet from the terminal with
proxychains BeamWallet

:wave:

**Comment by vcorem** [comment]
Hi,

Thanks for working on this!
I gave some more accurate instructions here: https://t.me/BeamPrivacy/314482
If you'll make the wallet work and write a detailed howto (for TAILS
noobs), the bounty will be 500 Beam.
If you'll make Beam node work as well ( + detailed howto for noobs), the
bounty will be 2K Beam.

Guy

**Comment by vcorem** [comment]
@sgaragagghu, see here and let me know if it's acceptable by you: https://t.me/BeamPrivacy/314583

**Comment by vcorem** [comment]
@tperalta82 and @sgaragagghu claimed this bounty. Basic tutorial here: https://medium.com/@tiagoperalta/beammw-and-node-in-tails-os-c348b398c544
