### ISSUE TITLE
We should show error message when wallet cannot connect to remote node

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#201]
FOR REMOTE NODE ONLY

Steps:
1. Select create or restore wallet, input recovery words and password 
2. Select connact to specific remote node - input incorrect peer
3. Try to connect to it
Expected: user should get error about timeout and suggestion to input another peer
smth like that https://github.com/BeamMW/beam/issues/134

@sasha-abramovich please provide text

**Comment by gingervik** [comment]
@jurijakimuk please, check if there any error now

**Comment by jurijakimuk** [comment]
Tested in masternet, 4255. 
Since during the restore we are no longer able to choose anything but local node - the issue was retested for the case of wallet creation. So after choosing the "specific remote" and providing an incorrect peer address: "kjhkjhkjh" - no error was shown and the wallet was loaded. No error message was shown. Expected was a message like this:  [message](https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c0e74f7fc0170b6cfe73fe2). 
So, as a result:
1. The indicator states "Node protocol error!".
![image](https://user-images.githubusercontent.com/41323026/51533645-8b9e3c00-1e54-11e9-87f1-4faef7147b27.png)

2. The Settings screen shows Invalid address error.
![image](https://user-images.githubusercontent.com/41323026/51533675-9c4eb200-1e54-11e9-9c6c-efafab22d0da.png)

**Comment by sasha-abramovich** [comment]
@alexandrashelenkova we need a way to display errors as above. Also, we've planned to always show the online status (including the settings screen), right?

**Comment by gingervik** [comment]
should be rechecked

**Comment by jurijakimuk** [comment]
Tested on 4819, masternet.
Issues found:
1) Going into a continuous loop when choosing "cancel" in the [popup](https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5c0e74f7fc0170b6cfe73fe2).
Zipped video:
[cancel.zip](https://github.com/BeamMW/beam/files/3137609/cancel.zip)

2) The wallet has crashed when choosing "cancel" in the popup, after providing a wrong peer like that "fgb".
Logs and dump files:
[beam_ui_19_05_02_13_18_30.log](https://github.com/BeamMW/beam/files/3137616/beam_ui_19_05_02_13_18_30.log)

**Comment by sasha-abramovich** [comment]
how about "Cannot connect to the node <IP> (<error message>)"?

**Comment by Zeke133** [comment]
> The wallet has crashed when choosing "cancel" in the popup, after providing a wrong peer like that "fgb".

This is not reproducible anymore.

Dialog buttons edited.

**Comment by gingervik** [comment]
can be closed
