### ISSUE TITLE
transactions never confirm if the receiving node isnt online

### ISSUE THREAD

**Issue by jl777** [BeamMW/beam#235]
**Bug description**
Sending to self works and the transaction is confirmed
Sending to an address not in the local node seems to require that the receiving node is online. 

**To Reproduce**
send transaction to an address for a node that is not online

**Current behaviour**
Even after a day and hundreds of blocks, it is not confirmed

**Expected behaviour**
It should confirm regardless of whether the destination wallet node is online or not, there are validating nodes active in the network

**Platform and build**
seems a problem with both osx and unix, likely windows too

**Comment by beam-mw** [comment]
Yes. Indeed in Mimblewimble there are no 'offline' or non interactive transactions. Both wallets are required to sign the transaction kernel.

Here is how it works now:
1. Two wallets create a transaction (over SBBS)
2. One of them (currently the receiver) sends it to the node it is connected to, which is online (otherwise transaction will not be sent)
3. Node validates the transaction and sends it to the next random node in Dandelion stem phase
4. After few hops transaction is fluffed to all peers and is propagated through the network

**Comment by beam-mw** [comment]
Also there is a difference between the node and the wallet, which is a bit different from other systems. The wallet is not required to run a node. To create the transaction both sender and receiver wallet should be online (though in case of Beam not necessarily at the same time)
