### ISSUE TITLE
Transaction status is "Failed" on Sender while Receiver is "Confirmed"

### ISSUE THREAD

**Issue by appkoders** [BeamMW/beam#330]
**Bug title**
Transaction status is inconsistent between the 2 parties. It is "Failed" on Sender while Receiver is "Confirmed"

**Bug description**
When I send a transaction its status changed to "Failed" on the sender's wallet while on the Receiver it is marked as "Confirmed" and the balance is appearing as normal on the receiver. Sometime its reversed, the sender's status is "Confirming" and  "Failed" on the receiver but not that severe as the "Confirming" status will Fail after 24 hours but still why would it wait that long.

**To Reproduce**
Steps to reproduce the behaviour:
Cant really reproduce as it happens randomly

**Expected behaviour**
Both sides should display the same status of the transaction

**Platform and build**
* Windows 10
* OS version
* BEAM Build number 1.0.3976(Security update)

**Configuration, log, memory dump files (if applicable)**
Add relevant files. The filenames and locations are described here: https://github.com/BeamMW/beam/wiki/Folder-and-file-locations

**Log file(s) (if applicable)**
Add relevant log file(s),  located in the `logs` folder.
[receiver.log](https://github.com/BeamMW/beam/files/2746248/receiver.log)
[sender_logs.log](https://github.com/BeamMW/beam/files/2746249/sender_logs.log)

**Screenshots (if applicable)**
Add screenshots that illustrate a problem you've found.
![receiver](https://user-images.githubusercontent.com/2902829/50982752-df498500-1538-11e9-9c38-bc6a1c0e10d7.png)
![sender](https://user-images.githubusercontent.com/2902829/50982755-df498500-1538-11e9-93ee-81271b7d96a6.jpg)

**Comment by alesito85** [comment]
Do you have access to both wallets? Is full balance spendable on both wallets?

**Comment by appkoders** [comment]
I already asked the receiver to try and spend it. I will try spending on the sender's wallet. Will let you know how it goes.

**Comment by valdok** [comment]
Hi @appkoders.
First and foremost, there is no way the receiver could actually get the coins without you actually spent them. No value can be "lost", so  - please don't worry.

Your specific transaction can be identified by the KernelID=d8ffc316f32755800ecfd9f6bfe918ab3999205ce7660ea0ca80439a627a0898

According to the logs of both sender and receiver the transaction was indeed broadcasted. And according to the blockchain explorer, it was actually included in this block (10337):

https://explorer.beam.mw/block/3b56ac3265c6c41c71061dff0528553d507777d07aea0f0da8348dbd634b8cc9

Now, since the sender wallet was connected to its owned node, which scans the blockchain (which is a recommended mode) - it noticed the change in your coins:

> I 2019-01-10.23:28:55.942 CoinID: Key=chng-0:1546881458000971, Value=862668334 Maturity=10335 Spent
> I 2019-01-10.23:28:55.960 CoinID: Key=chng-0:1546881458000977, Value=492942737 Maturity=10337 Confirmed
> 

Means, you spent a coin with value 8,62668334 and got a confirmed change with value 4,92942737. 
So that, no doubt, the transaction has completed successfully.

Now, the problem is that your wallet is "confused", and shows the transaction as failed. We identified a possible reason for this, and working on the fix, as well as other important features, hopefully will release all this soon.

Meanwhile you **CAN** use the change output.

**Comment by valdok** [comment]
@appkoders 
yes, you can always look for the KernelID.

In addition if you run with your owned node, you would see in the log file "CoinID: ..." - which corresponds to the actual changes of your UTXOs, gathered from the blockchain.

You can also look on your UTXOs list in the UI wallet, note the "Height" - it corresponds to the blockchain height at which it was received/spent.

Regarding the CLI - I believe it's susceptible to the same problems as the UI.
But, as I said, we're working to fix all this.

**Comment by medlynx** [comment]
Same problem.
![image](https://user-images.githubusercontent.com/36545972/50987320-6a675280-151a-11e9-935b-e237b4f23a5f.png)

**Comment by appkoders** [comment]
When do you think a fix can be made? Because right now I cant leave my pools payment system on automatic as if it encounters this problem then it will definitely send them again to the miner.

Aside from the two ways you mentioned to check if the TX was completed(which I dont think I can use for automation). Is there any other way specially an API call that I can use to check if the payment really failed so I can still enable our payment system.

**Comment by alesito85** [comment]
Maybe an API call that would look for tx kernel ID on the node could help for automation?

**Comment by valdok** [comment]
So, you're talking about pool payment system. Now I understand why the values were so weird :)

Regarding the release times - I can't tell you, since I'm not the one that decides. But we're working specifically on this right now, to release it ASAP.

We'll also include the cryptographic signature in the wallet, which actually proves that the receiver got the payment in case of a dispute.

**Comment by valdok** [comment]
If you are sure you paid him (i.e. the address is correct), then the UTXOs should definitely appear in his wallet after restore, or even without restore if he runs his own node (i.e. not in SPV mode).

If the kernelID isn't even shown in his wallet - then perhaps he already did the restore (during restore only UTXOs are restored, not the tx history).

Note however: right now even if you show your wallet with this kernelID, and show that it's in the blockchain - this is not a proof! You could (theoretically) craft it yourself.

Hence in the next wallet release there will be a message that acknowledges receive of the payment by the transaction with this kernelID, **signed** by the private key of the receiving address.
That would be a proof.

**Comment by gingervik** [comment]
hi @appkoders 
new release is coming soon
please, check your wallet and let us know if you still have this problem
thank you
