### ISSUE TITLE
wallet api send from weird address

### ISSUE THREAD

**Issue by wsy2220** [BeamMW/beam#411]
We are sending transactions using wallet-api, but some txs got stuck with weird address

![395796485](https://user-images.githubusercontent.com/7259503/51801147-f8f70600-2274-11e9-9d38-430814e25aaf.jpg)

**Comment by nesbox** [comment]
I think the problem is a result of using uninitialized variable, `Send{ WalletID from}` field in this case. Let's look at your `api.patch` code:

``` patch
--- a/wallet/api_cli.cpp
+++ b/wallet/api_cli.cpp
@@ -185,12 +185,19 @@ namespace beam
             {
                 LOG_DEBUG() << "Send(" << id << "," << data.session << "," << data.value <<  "," << std::to_string(data.address) << ")";
 
-                WalletAddress senderAddress = wallet::createAddress(_walletDB);
-                _walletDB->saveAddress(senderAddress);
+                WalletID wid;
+                if (!data.from.IsValid()) {
+                    WalletAddress senderAddress = wallet::createAddress(_walletDB);
+                    _walletDB->saveAddress(senderAddress);
+                    wid = senderAddress.m_walletID;
+                }
+                else {
+                    wid = data.from;
+                }
 
                 ByteBuffer message(data.comment.begin(), data.comment.end());
 
-                auto txId = _wallet.transfer_money(senderAddress.m_walletID, data.address, data.value, data.fee, true, std::move(message));
+                auto txId = _wallet.transfer_money(wid, data.address, data.value, data.fee, true, std::move(message));
 
                 doResponse(id, Send::Response{ txId });
             }
```

Here you checking `from` field using `if (!data.from.IsValid())` and `IsValid()` may return `true` even for uninitialized memory.
As result we go here `wid = data.from;` and call `transfer_money` with corrupted sender address.
Please, use our offcial `tx_send` api code to send money from specified address or look how we do it at least (https://github.com/BeamMW/beam/blob/master/wallet/api.cpp#L127).
Thank you.

**Comment by nesbox** [comment]
info for QA, please test `tx_send` api with and without `from` field.

**Comment by Sergei-Beam** [comment]
checked

**Comment by wsy2220** [comment]
@nesbox We are using dynamic wallet id now. Thank you very much😄
