### ISSUE TITLE
Remove GPU miner from UI wallet

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#448]

**Comment by nipponaihito** [comment]
Question, why was this recommended? I just downloaded the wallet and thought GPU mining from the UI was a neat feature.

**Comment by gingervik** [comment]
@nipponaihito most of our users use pools for mining. built-in miner is not effective and there are no big chances to mine block with it

**Comment by gingervik** [comment]
checked

**Comment by mattmill30** [comment]
> @nipponaihito most of our users use pools for mining. built-in miner is not effective and there are no big chances to mine block with it

In which case, would it not make more sense to copy the approach taken by the Bytecoin wallet, of providing pool mining within the UI?

Otherwise, please would you update the Mining documentation. CPU mining is currently only detailed under the "Mining using desktop wallet" subheading -  https://documentation.beam.mw/en/latest/rtd_pages/user_mining_beam.html#mining-using-desktop-wallet

**Comment by gingervik** [comment]
@mattmill30 hi.
please, look at our documentation about using external mining (it's gor GPU)
https://documentation.beam.mw/en/latest/rtd_pages/user_mining_beam.html#mining-using-external-miner
