### ISSUE TITLE
QR code modifications

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#617]
1. add beam before address

example: beam:12d1a5d6dc54af1792dc67325aeb274c38c36e005c730b964e978f0d3afdfddbc26

2. add ability to generate receive address with amount

example: 12d1a5d6dc54af1792dc67325aeb274c38c36e005c730b964e978f0d3afdfddbc26?amount=12.102

need to discuss "beam:addr?amount=123"

**Comment by gingervik** [comment]
checked. need to be done on mobile devices

**Comment by gingervik** [comment]
when user enter 1000000 as amount qr is modify it to ?amount=1e+6

**Comment by anatolse** [comment]
updated wiki
https://github.com/BeamMW/beam/wiki/Beam-URI-scheme

**Comment by sasha-abramovich** [comment]
for the "receive" screen design there was something a while ago (done for atomic swap and can be reused):
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5bd18f9c140d6a09ac8bd6dd

at least, the amount should be called "receive amount", the rest of the design can be opened as an improvement and be fixed in the next sprint.

**Comment by gingervik** [comment]
@anatolse please, rename transaction amount to "Receive amount (optional)"

**Comment by gingervik** [comment]
thank you. checked
