### ISSUE TITLE
Send confirmation design

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam#68]

**Comment by sasha-abramovich** [comment]
@gingervik AFAIK we've decided that every transaction will be signed by the recipient by default, hence no UX in the wallet is required. If agreed please close.

**Comment by gingervik** [comment]
Nice try @sasha-abramovich 
But here should be provided new design for this element
![image](https://user-images.githubusercontent.com/28015224/49136768-b5772e80-f2fb-11e8-9646-214d9ec5dac9.png)

**Comment by sasha-abramovich** [comment]
Thanks @gingervik! Screenshot helps! A totally different scenario indeed, thanks. I'm on it.

**Comment by sasha-abramovich** [comment]
@gingervik @BigRomanov I don't see why we need this dialog box: it's neither informative nor provides any added value (especially with these addresses that in general can be much longer and are faceless by design). Unless there are no objections I'd recommend to get rid of this dialog (it never presented on our screenshots in Zeplin). Please feel free to correct me if I'm wrong.

**Comment by gingervik** [comment]
discussed in Telegram
"We should do nice design where all transacton details are displayed" - @beam-mw

**Comment by sasha-abramovich** [comment]
as a quick solution: please have a dialog with 3 fields:

"Please review the transaction details":
Recipient: 
Amount:
Transaction fee:

Buttons: "send" , "cancel".

**Comment by alexandrashelenkova** [comment]
zpl.io/bA4YNwn

**Comment by gingervik** [comment]
checked
