### ISSUE TITLE
Locked Transactions issue

### ISSUE THREAD

**Issue by RaFuN** [BeamMW/beam#75]
**Bug description**
Received 100 Beam by a regular Transaction, for some reason it is locked and not available.
**To Reproduce**
1. Sent address to Vika (Nov 13, 10:28am), 
2. Received 100 coins immediately, The coins are in locked status (not sure what that means)

**Current behavior**

Dont have any more info other the provided above 

**Expected behavior**
Receive the coins that will become available a few min later 

**Configuration file (if applicable)**

**Log file(s) (if applicable)**
Added
[beam v1.0.3005 osx report.zip](https://github.com/BeamMW/beam/files/2580634/beam.v1.0.3005.osx.report.zip)

**Platform**
Mac

**Build**
Build number
1.0.3005
**Screenshots (if applicable)**
![2018-11-14_08-57-57](https://user-images.githubusercontent.com/39724250/48481721-3d970780-e817-11e8-9271-f58babbc182c.png)
![2018-11-14_13-48-29](https://user-images.githubusercontent.com/39724250/48481722-3d970780-e817-11e8-9b19-3b042c57c6f6.png)

**Comment by Sergei-Beam** [comment]
It's not a Bug. Because your 10 Beam still in In_Progress state, after completed system will return the change for you.

**How it works:**
You got 100 Beams from Vika as 1 coin
When you are sending  the 10 Beam, system locks all coins which included in transaction, in your case it is 100Beam
Then the system takes away your 10 + fee and generates the change for you as 89.99999 Beams
