### ISSUE TITLE
Add function to check the node sync status

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam#779]
1. Local node is running, but not updated to 100%. Example: 30%
2. Mobile app is connected to local node. Mobile app should show status of updating local node.
We receiving sometimes onSyncProgressUpdated 0/1, 1/1. But we need display always updating status, if node is not synced to 100%

**Comment by sasha-abramovich** [comment]
The wallet also probably should not refuse connections to "older" nodes but just show a warning that the user should verify manually that the node is fully synchronized with the blockchain. With the nodes that support a full protocol of exposing the sync status, full information should be displayed.

The node should expose sync completion percentage with the following numbers (so that the mobile wallet will have the flexibility in what to display): 
* Current number of blocks downloaded before the sync started
* Current number of total blocks downloaded since the sync started
* Total number of blocks
* Expected time to finish the sync

**Comment by anatolse** [comment]
@DenisDemyanko, use WalletClient::isSynced() to be sure that wallet is in correct state

**Comment by Denis-Asipenko** [comment]
checked
