### ISSUE TITLE
transaction pending currencies in my wallet

### ISSUE THREAD

**Issue by alexmelro** [BeamMW/beam#857]
good afternoon is as follows a few days ago I made two transactions for my beam desktop wallet and to this day are the two outstanding transactions in my wallet, says the currencies the status are incoming, but no available.
I liked your help, thanks and greetings.

**Comment by VladislavKulyba** [comment]
Hello,
Please, attach your logs and screenshot with transaction status (receiving, expired and etc.)

Regards,
Vlad Kulyba

**Comment by alexmelro** [comment]
Good evening, I will send you the screenshot, I do not know if I can do it because I have little practice, to this day both transactions are still pending, thank you very much if you can help me.

![20190920_232355](https://user-images.githubusercontent.com/46615619/65362682-4e1aca00-dc00-11e9-8b83-e87760b87928.jpg)

![20190920_232425](https://user-images.githubusercontent.com/46615619/65362672-40fddb00-dc00-11e9-99ec-8dde7d559e20.jpg)

**Comment by VladislavKulyba** [comment]
You didn't attach logs. Please, send it too.
Use this documentation to find it on your device
https://documentation.beam.mw/en/latest/rtd_pages/user_files_and_locations.html

**Comment by alexmelro** [comment]
good afternoon I will send you the logs, I believe this is what you need to see, thank you very much.
best regards
[beam_ui_19_09_08_15_07_24.log](https://github.com/BeamMW/beam/files/3638801/beam_ui_19_09_08_15_07_24.log)
[beam_ui_19_09_09_00_20_25.log](https://github.com/BeamMW/beam/files/3638802/beam_ui_19_09_09_00_20_25.log)
[beam_ui_19_09_09_20_28_27.log](https://github.com/BeamMW/beam/files/3638803/beam_ui_19_09_09_20_28_27.log)
[beam_ui_19_09_12_15_47_50.log](https://github.com/BeamMW/beam/files/3638804/beam_ui_19_09_12_15_47_50.log)
[beam_ui_19_09_13_19_14_57.log](https://github.com/BeamMW/beam/files/3638805/beam_ui_19_09_13_19_14_57.log)
[beam_ui_19_09_20_23_10_12.log](https://github.com/BeamMW/beam/files/3638807/beam_ui_19_09_20_23_10_12.log)

**Comment by VladislavKulyba** [comment]
Hello, you are using an old version of wallet. Please, follow this instructions:

1. You should download the latest version, which you could  find on our website https://www.beam.mw/downloads/mainnet-windows
2. You need to delete the node.db file since you are updating from a version older than 3.0. This file you could find following path, which you'll find in this documentation: https://documentation.beam.mw/en/latest/rtd_pages/user_files_and_locations.html
Be careful: this path could be hidden by default. If you don't know, how to make this folder visible, please try to use some guides like this:
https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files
3. Run the installer that you have downloaded. You'll see the screen with migration to the latest version process. It's better to choose automigration, because it will find the latest database that you used.
4. Just wait when full sync will be finished.

**Comment by alexmelro** [comment]
Good evening, I apologize for the delay in responding, but I tried a few times to find in windows the file I have to delete "node.db", but I can not, because I understand little computers there is another possible way to do it ?? I tried to delete the wallet Beam and reinstall again, but everything was the same, thanks for the help and best regards

**Comment by VladislavKulyba** [comment]
Hello, please, could you ask in telegram channel? Just describe your issue to show that it's you and we can solve it faster. https://t.me/BeamSupport

**Comment by gingervik** [comment]
can be closed
