### ISSUE TITLE
Transaction details screen for Atomic Swap

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam#887]
The general UX should be similar to the regular transaction details, the types of data to be displayed are:
* Transaction IDs for every BTC/LTC/QTUM transaction (lock/redeem/refund)
* Confirmation number for every BTC/LTC/QTUM transaction
* Kernel ID and other relevant data for BEAM

**Comment by gingervik** [comment]
Also please add comment 
![image](https://user-images.githubusercontent.com/28015224/66029582-3dbff480-e508-11e9-9a00-fd567c69586e.png)

**Comment by sasha-abramovich** [comment]
When available, Bitcoin UTXO ID should be shown, so that customer can check this ID externally and cancel the transaction when required.

**Comment by Sergei-Beam** [comment]
@Zeke133 Please add the following data to the tx details:
- Transaction ID
-  I think we also should add Transaction fee and Transaction fee rate, just for information because after clicking publish offer user can't be able to see that

Bugs
![image](https://user-images.githubusercontent.com/44496108/66843302-43d8bb00-ef75-11e9-874c-ba7d1da4748b.png)
1. Beem redeem Kernel ID should be displayed, now it's missed
2. There is no sense to show 0 confirmations for the side which don't need to know it OR show it correct for both sides

**Comment by Sergei-Beam** [comment]
@Zeke133 please, add also the error reason for failed/expired transaction as it is done for usual Tx

**Comment by Sergei-Beam** [comment]
@Zeke133 please, add also information about BEAM Refund transaction ID because currently there's no such info 
![image](https://user-images.githubusercontent.com/44496108/67486937-a4eb4780-f675-11e9-97af-e20aa9de674d.png)

Also don't forget about Error reason https://github.com/BeamMW/beam/issues/887#issuecomment-544871788

**Comment by Roberrtt** [comment]
Not done
please, add also information about BEAM Refund transaction ID because currently there's no such info

**Comment by Roberrtt** [comment]
Checked
